name: Deply workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to gh-pages branch
        working-directory: ./build
        run: |
          ls- f .
          git checkout main
          echo "LAST_COMMIT_MESSAGE=$(echo git log -1 --pretty=%B)"
          echo $LAST_COMMIT_MESSAGE
