name: Deply workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Push to gh-pages branch
      working-directory: ./build
    - run: ls- f .
    - run: git checkout main
    - run: echo "LAST_COMMIT_MESSAGE=$(echo git log -1 --pretty=%B)"
    - run: echo $LAST_COMMIT_MESSAGE
